### ISSUE TITLE
SSL Protocol error on Bitbucket Link

### ISSUE THREAD

**Issue by oguzeray** [RehabMan/OS-X-Null-Ethernet#11]
Links on your BitBucket redirects to "https://bbuseruploads.s3.amazonaws.com/..." which responds with "ERR_SSL_PROTOCOL_ERROR".
Would you be willing to fix that or Am I doing something wrong.

**Comment by RehabMan** [comment]
I'm not really doing hackintosh anymore, but just checked and the downloads are working fine here.  Must be a problem on your end or a temporary problem with bitbucket.
