### ISSUE TITLE
Question about the first method

### ISSUE THREAD

**Issue by mmefriantine** [RehabMan/OS-X-Null-Ethernet#2]
I do not understand that part. 
To install the SSDT:

Chameleon: Place in /Extra/ssdt.aml or /Extra/ssdt-1.aml, /Extra/ssdt-2.aml, depending on what SSDTs you already have installed.

What do you mean by place in? 
Do I need a tool for that?

Also I use chimera from multibeast as a boot loader. Is it the same as chameleon?

Thank you 
Have a great day
Marc

**Comment by RehabMan** [comment]
You can copy files with Finder.

**Comment by mmefriantine** [comment]
So I replace /Extra/ssdt.aml by your ssdt or I copy your ssdt in /Extra?

**Comment by RehabMan** [comment]
It depends on whether you want to keep the functionality provided by the SSDT you already have there.

If that SSDT.aml is for your CPU, you should keep it (seems obvious).

In that case, you'll have to name the new SSDT (for NullEthernet) to SSDT-1.aml.

**Comment by mmefriantine** [comment]
Sorry it wasn't obvious for me. Everything works like a charm!
Thank you
