### ISSUE TITLE
Capability on Sierra 10.12.6 ?

### ISSUE THREAD

**Issue by yo1995** [RehabMan/OS-X-Null-Ethernet#4]
Don't know if it's proper to ask here, but I failed to apply this kext with corresponding SSDT-rmne.aml on my sierra system. My configuration is xps-9560 with killer Ethernet card not-driven.
Other successful applications with the method of modifying DSDT were reported for xps-9560. I followed the How to Install (DSDT/SSDT method) part in the description yet to found nothing in my network setting panel. I also followed the http://buildingahackintosh.weebly.com/networking-in-sierra.html
to take a second try but failed again...
I wonder if something is wrong with my configuration, but I don't know how to identify the problem due to a lack of knowledge of the ssdt methods. I hope if the author could give me some instruction. Many thanks. :smile:

**Comment by RehabMan** [comment]
This is not the place for troubleshooting.
Use the forums (read the README).
