### ISSUE TITLE
No need to attach to existing PCI device

### ISSUE THREAD

**Issue by jpap** [RehabMan/OS-X-Null-Ethernet#5]
I was about to create something similar for a real macOS system, and found this project.  I am using it to assign a DNS provider when other network interfaces are down.  It looks like the only way to do that is with a dummy ethernet device.

By using the `IOProviderClass -> IOResources` IOKit personality key/value pair, you can match the driver without a PCI device.  This works well for me on my MacBook Pro running 10.12.6 (16G29).

The `IOKitPersonalities > NullEthernet` info.plist dictionary then becomes,
```
<dict>
	<key>CFBundleIdentifier</key>
	<string>${MODULE_NAME}</string>
	<key>IOClass</key>
	<string>org_rehabman_NullEthernet</string>
	<key>IOMatchCategory</key>
	<string>org_rehabman_NullEthernet</string>
	<key>IOProviderClass</key>
	<string>IOResources</string>
	<key>Model</key>
	<string>NullEthernet</string>
	<key>Vendor</key>
	<string>RehabMan</string>
</dict>
 ```
where I've removed the `IONameMatch` key/value pair because I don't think you need it anymore; why don't you just configure the MAC address from the property list here always? (I'm happy using the hard-coded default.)

For reference, have a look at the [Creating a Generic Kernel Extension with Xcode](https://developer.apple.com/library/content/documentation/Darwin/Conceptual/KEXTConcept/KEXTConceptIOKit/iokit_tutorial.html#//apple_ref/doc/uid/20002366-98320-CHDHAEDI) tutorial.

**Comment by RehabMan** [comment]
I added NullEthernetForce.kext and associated code for this same idea, but it doesn't work, as it doesn't present itself as built-in.

Eventually, I gave up, mostly because I didn't need it anyway.

You can continue with your own experiments.
