### ISSUE TITLE
Remove redundant kext dependencies

### ISSUE THREAD

**Issue by jpap** [RehabMan/OS-X-Null-Ethernet#6]
Looks like there are some dependencies left over from Mieze's codebase; all you need are:
```
	<key>OSBundleLibraries</key>
	<dict>
		<key>com.apple.iokit.IOACPIFamily</key>
		<string>1.4</string>
		<key>com.apple.iokit.IONetworkingFamily</key>
		<string>3.2</string>
		<key>com.apple.kpi.iokit</key>
		<string>16.7</string>
		<key>com.apple.kpi.libkern</key>
		<string>16.7</string>
	</dict>
```
that are listed by the `kextlibs --xml NullEthernet.kext` command.

**Comment by RehabMan** [comment]
Seems no harm in having the extra entries.
No advantage to removing them (all risk).
Therefore... won't fix.
