### ISSUE TITLE
Chameleon DSDT/SSDT install, can not find /Extra folder

### ISSUE THREAD

**Issue by yi** [RehabMan/OS-X-Null-Ethernet#8]
Hi, sorry to bother. I'm trying to DSDT/SSDT install this NullEthernet on my hackintosh. It's using Chameleon bootloader. But the problem is there is NO /Extra folder in system root.

Could you shed some light on this? 

![2017-09-14_01-33-07](https://user-images.githubusercontent.com/9838/30391527-4f2de796-98ec-11e7-9501-6092bf2aba28.jpg)

**Comment by RehabMan** [comment]
If you don't have an /Extra, create it (sudo mkdir /Extra)
